### ISSUE TITLE
Adding total count in non-relay pagination

### ISSUE THREAD

**Issue by stoicsleuth** [strawberry-graphql/strawberry-django#442] opened 2023-12-18 06:24 UTC
## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

(Previously mentioned in https://github.com/strawberry-graphql/strawberry-graphql-django/issues/408)

Our project very extensively uses `strawberry-graphql-django` to expose nodes on our models. Earlier, we faced some issues related to pagination since the library only exposed `totalCount` of paginated results with Relay while we hadn’t built our project on top of Relay.

We had thus overridden some class methods with a previous version of `strawberry-graphql-django`, which again started breaking when we tried to upgrade to the latest one.
Since overriding methods for pagination is not future-proof, I wanted to propose if we can accommodate 'totalCount' for pagination in the library without going through the Relay route.

I can try creating a PR for it if the idea aligns with the library’s roadmap.
Let me know your thoughts.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/442">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/442/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/442/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment] 2023-12-18 14:52
Hey @stoicsleuth ,

First of all:
> Since overriding methods for pagination is not future-proof

We are not planning on breaking API for those in the future. The only reason for such breakeage would be if we had to do something which is incompatible with the current API

But having said that, sure, I think it is fair to have an alternative pagination structure which can expose extra data (such as `totalCount`) and is not reliant on relay.

PRs are totally welcomed! :)

**Comment by bellini666** [comment] 2024-06-15 14:52
This is mostly a duplicate of https://github.com/strawberry-graphql/strawberry-django/issues/408, so closing it for sanity :)

**Closed by bellini666** 2024-06-15 14:52 UTC
