### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by ramzitannous** [strawberry-graphql/strawberry-django#80] opened 2021-12-24 17:52 UTC
Is this Library ready for production usage, is it supported enough?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/80">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/80/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/80/pledge.svg">
</picture>
</a>

**Comment by Lucasmiguelmac** [comment] 2022-01-30 13:28
The maintainers certainly don't consider that since the library's version is < 1.0.0.

Anyways, the dev experience with this library is unmatchable. It's a shame we lack documentation

**Comment by la4de** [comment] 2022-02-19 19:31
Right, Strawberry core and django integration, both are still under development. Type generation from models is already quite stable but other areas may still change.

I agree with you that we are lacking documentation. It would be nice to see contributions there as well 😄

**Comment by ccsv** [comment] 2022-07-15 08:45
Not ready for production. I would go for Graphene if you want graphql for production.

There are still issues that are not addressed like nested create mutations, django choices / integer choices / enum support, many to many support query issues with prefetching, permission issues, 

I have to say it is easier to write than Ariadne or Graphene but the issue is the docs are not too great.

**Comment by bellini666** [comment] 2022-07-15 13:47
Hey @ccsv ,

Although this lib really lacks the support for everything you mentioned here, all of those features/issues are implemented/solved in [strawberry-django-plus](https://github.com/blb-ventures/strawberry-django-plus), which is also [going to be merged really soon](https://github.com/strawberry-graphql/strawberry-graphql-django/issues/139) into this repo.

I have a really big production project running using `strawberry-django-plus`, async django and even a lot of subscriptions. Using strawberry, which also enforces good typing practices, has allowed us to develop that project a lot faster than we ever could when we were using graphene (which not only has a legacy way of defining things, it is very error prone due to its lack of typing support). I'm planning on writing a blog post regarding how we do things here, because I think one thing that this integration (and also my own lib) is lacking is a good amount of examples on how to do common and advanced things.

**Comment by nrbnlulu** [comment] 2022-07-29 06:12
> and even a lot of subscriptions.   
@bellini666 Your subscriptions are django specific or just the plain strawberry, ASAIK  either SD or SD+ doesn't support subscriptions at the moment.

**Comment by bellini666** [comment] 2022-07-29 15:30
> > and even a lot of subscriptions.
> 
> @bellini666 Your subscriptions are django specific or just the plain strawberry, ASAIK either SD or SD+ doesn't support subscriptions at the moment. #155

Subscriptions support is going to be available soon using channels: https://github.com/strawberry-graphql/strawberry/pull/1407

It can already be used with pre-releases also.

**Comment by bellini666** [comment] 2024-06-15 14:39
For anyone following this,

I consider this project, and strawberry itself, to be production ready for some time now. Even though we have still not released a `1.0` release, that is just a matter of time TBH and we are not planning on doing major changes to both in the near future.

Going to mark this as solved, but feel free to ping this and/or open new issues for any other issues/questions you might have

**Closed by bellini666** 2024-06-15 14:39 UTC
